from pathlib import Path

PROJECT_DIR = Path(__file__).parents[2]

DATA_DIR = PROJECT_DIR / "data"

GENERATED_DATA_DIR = DATA_DIR / "generated"
GENERATED_DATA_DIR.mkdir(parents=True, exist_ok=True)

PIPELINE_OUTPUT_DIR = GENERATED_DATA_DIR / "pipeline"

INCLUDED_DATA_DIR = DATA_DIR / "included"

TEST_CORPUS_DIR = PROJECT_DIR / "tests" / "corpus"

CEDICT_URL = "https://www.mdbg.net/chinese/export/cedict/cedict_1_0_ts_utf-8_mdbg.zip"
CEDICT_ZIP = GENERATED_DATA_DIR / "cedict_1_0_ts_utf-8_mdbg.zip"
CEDICT_DIR = CEDICT_ZIP.with_suffix("")
CEDICT_FILE = CEDICT_DIR / "cedict_ts.u8"

CHUNOM_CHAR_FILE = INCLUDED_DATA_DIR / "chunom_org" / "char_data.csv"
CHUNOM_VOCAB_FILE = INCLUDED_DATA_DIR / "chunom_org" / "standard-list.csv"

# Vietnamese (Hán-Việt / Sino-Vietnamese) source data
VI_DATA_DIR = INCLUDED_DATA_DIR / "vi"
VI_RAW_DIR = VI_DATA_DIR / "raw"
# WinVNKey Hán-Việt reading databases (char -> Hán-Việt reading). These are NOT
# shipped with the repo -- they transcribe in-copyright dictionaries, so they are
# used only when USE_WINVNKEY_READINGS is enabled for personal use, and must be
# supplied locally here (UTF-8, converted from the UTF-16 originals).
VI_WINVNKEY_FILES = [
    VI_RAW_DIR / "han-viet-thanh-son-le-3.04.txt",
    VI_RAW_DIR / "han-viet-hoc-d-ngo.txt",
    VI_RAW_DIR / "han-viet-trad-supplement-2.02.txt",
]
# Merged, normalized char -> Hán-Việt reading table (generated by
# data/vietnamese.py as a review artifact; not committed)
VI_READINGS_FILE = GENERATED_DATA_DIR / "vi_han_viet_readings.tsv"

# Unicode L2/23-251 corrections to Unihan kVietnamese values (166 chars, each with
# readings to remove and/or add). Permissively-licensed Unicode working-group data,
# extracted from https://www.unicode.org/L2/L2023/23251-kvietnameseCorr.pdf
VI_KVIET_CORRECTIONS_FILE = VI_DATA_DIR / "kvietnamese_corrections.tsv"

# Vietnamese word/syllable frequency lists (downloaded, cached in generated/)
# Leipzig Corpora Collection (CC BY) -- formal/written register, primary signal.
# The 1M-sentence news corpus is used both for syllable frequency (words.txt) and,
# crucially, for true per-word frequency by counting each Sino-Vietnamese word as a
# contiguous syllable n-gram in the sentences file.
LEIPZIG_VI_CORPUS = "vie_news_2022_1M"
LEIPZIG_VI_URL = (
    f"https://downloads.wortschatz-leipzig.de/corpora/{LEIPZIG_VI_CORPUS}.tar.gz"
)
LEIPZIG_VI_TARBALL = GENERATED_DATA_DIR / f"{LEIPZIG_VI_CORPUS}.tar.gz"
LEIPZIG_VI_DIR = GENERATED_DATA_DIR / LEIPZIG_VI_CORPUS
LEIPZIG_VI_WORDS_FILE = LEIPZIG_VI_DIR / f"{LEIPZIG_VI_CORPUS}-words.txt"
LEIPZIG_VI_SENTENCES_FILE = LEIPZIG_VI_DIR / f"{LEIPZIG_VI_CORPUS}-sentences.txt"
# HermitDave FrequencyWords / OpenSubtitles (CC BY-SA) -- colloquial, secondary signal
OPENSUBS_VI_URL = (
    "https://raw.githubusercontent.com/hermitdave/FrequencyWords/"
    "master/content/2018/vi/vi_50k.txt"
)
OPENSUBS_VI_FILE = GENERATED_DATA_DIR / "vi_opensubtitles_50k.txt"

# vnedict (Paul Denisowski, CC BY 3.0): Vietnamese->English; used to confirm that a
# Chinese word, read with Hán-Việt readings, is an actual Vietnamese word.
VNEDICT_URL = "http://www.denisowski.org/Vietnamese/vnedict.txt"
VNEDICT_FILE = GENERATED_DATA_DIR / "vnedict.txt"

COMPONENT_OVERRIDE_FILE = INCLUDED_DATA_DIR / "manual_components.json"

EDICT_FREQ_URL = "http://ftp.edrdg.org/pub/Nihongo/edict-freq-20081002.tar.gz"
EDICT_FREQ_TARBALL = GENERATED_DATA_DIR / "edict-freq-20081002.tar.gz"
EDICT_FREQ_DIR = EDICT_FREQ_TARBALL.with_suffix("").with_suffix("")
EDICT_FREQ_FILE = EDICT_FREQ_DIR / "edict-freq-20081002"

JUN_DA_CHAR_FREQ_URL = (
    "https://lingua.mtsu.edu/chinese-computing/statistics/char/list.php"
)
JUN_DA_CHAR_FREQ_FILE = GENERATED_DATA_DIR / "jun_da_char.tsv"

KENGDIC_DATA_PACKAGE_URL = (
    "https://raw.githubusercontent.com/garfieldnate/kengdic/master/datapackage.json"
)

KO_ED_CHARS_FILE = INCLUDED_DATA_DIR / "kyoyuk_hanja.csv"

JP_VOCAB_OVERRIDE = INCLUDED_DATA_DIR / "jp_vocab_override.json"

LIB_HANGUL_URL = "https://github.com/libhangul/libhangul/archive/master.zip"
LIB_HANGUL_ZIP_FILE = GENERATED_DATA_DIR / "libhangul-master.zip"
LIB_HANGUL_DIR = LIB_HANGUL_ZIP_FILE.with_suffix("")

PHONETIC_COMPONENTS_FILE = GENERATED_DATA_DIR / "components_to_chars.tsv"

UNIHAN_FILE = GENERATED_DATA_DIR / "unihan.json"
