[tool.poetry]
name = "uniunihan-db"
version = "0.1.0"
description = ""
authors = ["Nathan Glenn <garfieldnate@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^2.10.1"
flake8 = "^3.8.4"
mypy = "^0.790"
black = "^20.8b1"
isort = "^5.6.4"
pre-commit = "^2.7.1"
unihan-etl = "^0.11.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths="test"
