name: Build Book

# Build book and perhaps upload to GitHub pages

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install poetry
        run: pip install poetry
      - name: Install dev dependencies
        run: poetry install
      - name: Collate
        run: poetry run poe collate
      - name: Build Book
        run: poetry run poe build_book
        # TODO: upload debug-level logs, too
    #   - name: Move debug logs
    #     run: cp data/generated/debug-log*.txt data/generated/book/
      - name: Upload results to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./data/generated/book
