name: Verification

# Run linting and unit tests

on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install poetry
        run: pip install poetry
      - name: Install dev dependencies
        run: poetry install
      - name: Run verifications
        uses: pre-commit/action@v2.0.3
